### ISSUE TITLE
Is it possible to delete lines(edges)?

### ISSUE THREAD

**Issue by guanwei514** [dylantsouy/draw-flow-list#1]
It's not able to delete the selected line (edge). When I want to delete the seleted line, it will delete the all connected nodes at the same time. Could it be deleted separatly?

**Comment by dylantsouy** [comment]
@guanwei514 yes, I'm currently working on this function, I will let you know when release a new version

**Comment by dylantsouy** [comment]
Hi @guanwei514 I already close this issue, you can remove edge now!
